### ISSUE TITLE
WITH FRESH INSTALL OF ESX I GET THIS ERROR ON esx_addoninventory

### ISSUE THREAD

**Issue by hasidu** [esx-framework/esx_addoninventory#2]
![image](https://user-images.githubusercontent.com/72035642/221409398-34663b47-fc3e-4eb7-b8b0-ceb50f6f7f44.png)

how i can fix this problem ?

**Comment by hasidu** [comment]
solved

**Comment by DocBurN** [comment]
what did you do to fix it ?

**Comment by hasidu** [comment]
just check your sever cfg
